### PR TITLE
Initial EDA

### PR DESCRIPTION
**Pull request by danmurphy1217**

### CODE REVIEW

**Comment by yuvalpinter** [comment]
Hi Dan,

Thanks for this, I'll look into the code later, in the meantime could you please remove the `nytwit_venv` directory, and explain the changes you made to the dataset file? [If they're justified, we'll bump the version; if not, they need to be removed as well]

Thanks,
- Yuval

**Comment by danmurphy1217** [comment]
> Hi Dan,
> 
> Thanks for this, I'll look into the code later, in the meantime could you please remove the `nytwit_venv` directory, and explain the changes you made to the dataset file? [If they're justified, we'll bump the version; if not, they need to be removed as well]
> 
> Thanks,
> 
> * Yuval

Hi Yuval,
Just for clarification, is there a specific reason you want the virtual environment to be removed? Not a problem to do so, I'm just wondering. 

Regarding the dataset, any changes made did not affect the actual .tsv. I loaded the .tsv  first (into 'data') and then I put that in a DataFrame (called 'df'). I made some changes to df (nothing major, just some re-structuring of the "Time" column to look at how many words were uploaded/day, etc.), but nothing to 'data.' Let me know If you have any other questions!

**Comment by BayesForDays** [comment]
Hi Dan,

Could you provide a bit more information about what your pull request is going to do for the main repository? In checking it out this seems to just be some basic statistics and I'm not seeing a place where the components are really integrated. In light of this perhaps a notebook containing the functions you define in `init.py` could be more useful to the audience?

Since the .tsv is not fundamentally changed I think the dataset file should be untracked for this commit.

I can't speak for Yuval but I also think the virtual environment should be untracked for this commit -- if you want to make your code reproducible for the main branch and there are dependencies that your code requires, you could create a `requirements.txt` file or something maybe.

--Cassie

**Comment by danmurphy1217** [comment]
Hi Cassie, 
The main reason for the initial work I did in init.py was for exploratory data analysis. I was simply looking at the dataset and getting a grasp for what it contains and some of the underlying stats within. Then, my plan was to reach out to you/Yuval and see what some of the detailed things are that you wanted to see people do with this dataset. 

Moving forward, just to clarify, I can create a **requirements.txt** and transfer the code I wrote to a **jupyter notebook**. Then, I'll reach back out. Does this sound good or is there anything else you'd also like me to do? Thank you!

**Comment by yuvalpinter** [comment]
Yes, this sounds good. Thanks again!

**Comment by BayesForDays** [comment]
Dan, could you close this PR and then reopen a new PR once you have made the proposed changes?

**Pull request closed without merging**
